// every ideology has a position on the test's three axes (0-100 scale):
//   economics : Equality <-> Markets      (Left/Right)
//   cultural  : Progress <-> Tradition     (Progressive/Conservative)
//   worldview : Liberty  <-> Authority     (matches the Philosophical axis)
ideologies = [
    { "name": "Anarcho-Communism", "stats": { "economics": 100, "cultural": 90, "worldview": 75 } },
    { "name": "Libertarian Communism", "stats": { "economics": 100, "cultural": 80, "worldview": 75 } },
    { "name": "Trotskyism", "stats": { "economics": 100, "cultural": 80, "worldview": 80 } },
    { "name": "Marxism", "stats": { "economics": 100, "cultural": 80, "worldview": 55 } },
    { "name": "De Leonism", "stats": { "economics": 100, "cultural": 80, "worldview": 30 } },
    { "name": "Leninism", "stats": { "economics": 100, "cultural": 70, "worldview": 30 } },
    { "name": "Stalinism/Maoism", "stats": { "economics": 100, "cultural": 60, "worldview": 10 } },
    { "name": "Religious Communism", "stats": { "economics": 100, "cultural": 30, "worldview": 40 } },
    { "name": "State Socialism", "stats": { "economics": 80, "cultural": 70, "worldview": 30 } },
    { "name": "Theocratic Socialism", "stats": { "economics": 80, "cultural": 20, "worldview": 40 } },
    { "name": "Religious Socialism", "stats": { "economics": 80, "cultural": 20, "worldview": 60 } },
    { "name": "Democratic Socialism", "stats": { "economics": 80, "cultural": 80, "worldview": 50 } },
    { "name": "Revolutionary Socialism", "stats": { "economics": 80, "cultural": 70, "worldview": 35 } },
    { "name": "Libertarian Socialism", "stats": { "economics": 80, "cultural": 80, "worldview": 80 } },
    { "name": "Anarcho-Syndicalism", "stats": { "economics": 80, "cultural": 80, "worldview": 75 } },
    { "name": "Left-Wing Populism", "stats": { "economics": 60, "cultural": 70, "worldview": 35 } },
    { "name": "Theocratic Distributism", "stats": { "economics": 60, "cultural": 20, "worldview": 35 } },
    { "name": "Distributism", "stats": { "economics": 60, "cultural": 20, "worldview": 50 } },
    { "name": "Social Liberalism", "stats": { "economics": 60, "cultural": 80, "worldview": 60 } },
    { "name": "Christian Democracy", "stats": { "economics": 60, "cultural": 30, "worldview": 55 } },
    { "name": "Social Democracy", "stats": { "economics": 60, "cultural": 80, "worldview": 65 } },
    { "name": "Progressivism", "stats": { "economics": 60, "cultural": 100, "worldview": 70 } },
    { "name": "Anarcho-Mutualism", "stats": { "economics": 60, "cultural": 70, "worldview": 75 } },
    { "name": "National Totalitarianism", "stats": { "economics": 50, "cultural": 50, "worldview": 10 } },
    { "name": "Global Totalitarianism", "stats": { "economics": 50, "cultural": 50, "worldview": 40 } },
    { "name": "Technocracy", "stats": { "economics": 60, "cultural": 70, "worldview": 40 } },
    { "name": "Centrist", "stats": { "economics": 50, "cultural": 50, "worldview": 50 } },
    { "name": "Liberalism", "stats": { "economics": 50, "cultural": 60, "worldview": 60 } },
    { "name": "Religious Anarchism", "stats": { "economics": 50, "cultural": 20, "worldview": 75 } },
    { "name": "Right-Wing Populism", "stats": { "economics": 40, "cultural": 30, "worldview": 30 } },
    { "name": "Moderate Conservatism", "stats": { "economics": 40, "cultural": 30, "worldview": 45 } },
    { "name": "Reactionary", "stats": { "economics": 40, "cultural": 10, "worldview": 40 } },
    { "name": "Social Libertarianism", "stats": { "economics": 60, "cultural": 70, "worldview": 75 } },
    { "name": "Libertarianism", "stats": { "economics": 40, "cultural": 60, "worldview": 70 } },
    { "name": "Anarcho-Egoism", "stats": { "economics": 40, "cultural": 50, "worldview": 75 } },
    { "name": "Nazism", "stats": { "economics": 40, "cultural": 5, "worldview": 0 } },
    { "name": "Autocracy", "stats": { "economics": 50, "cultural": 50, "worldview": 20 } },
    { "name": "Fascism", "stats": { "economics": 40, "cultural": 20, "worldview": 20 } },
    { "name": "Capitalist Fascism", "stats": { "economics": 20, "cultural": 20, "worldview": 20 } },
    { "name": "Conservatism", "stats": { "economics": 30, "cultural": 20, "worldview": 40 } },
    { "name": "Neo-Liberalism", "stats": { "economics": 30, "cultural": 60, "worldview": 40 } },
    { "name": "Classical Liberalism", "stats": { "economics": 30, "cultural": 80, "worldview": 60 } },
    { "name": "Authoritarian Capitalism", "stats": { "economics": 20, "cultural": 40, "worldview": 25 } },
    { "name": "State Capitalism", "stats": { "economics": 20, "cultural": 50, "worldview": 40 } },
    { "name": "Neo-Conservatism", "stats": { "economics": 20, "cultural": 20, "worldview": 30 } },
    { "name": "Fundamentalism", "stats": { "economics": 20, "cultural": 5, "worldview": 30 } },
    { "name": "Libertarian Capitalism", "stats": { "economics": 20, "cultural": 60, "worldview": 65 } },
    { "name": "Market Anarchism", "stats": { "economics": 20, "cultural": 50, "worldview": 75 } },
    { "name": "Objectivism", "stats": { "economics": 10, "cultural": 40, "worldview": 70 } },
    { "name": "Totalitarian Capitalism", "stats": { "economics": 0, "cultural": 50, "worldview": 15 } },
    { "name": "Ultra-Capitalism", "stats": { "economics": 0, "cultural": 50, "worldview": 45 } },
    { "name": "Anarcho-Capitalism", "stats": { "economics": 0, "cultural": 50, "worldview": 75 } }
];
